export const TRACING_ASYNC_CONTEXT_SEGMENT = "TRACING_ASYNC_CONTEXT_SEGMENT";
export const TRACING_ASYNC_CONTEXT_SUBSEGMENT =
  "TRACING_ASYNC_CONTEXT_SUBSEGMENT";

export const XRAY_CLIENT = "XRAY_CLIENT";
